#include "../common.hlsl"

[[vk::binding(0, 9)]]
cbuffer type_ctime_cb : register(b0, space9)
{
    float ctime_cb_time : packoffset(c0);
    float ctime_cb_sdr_scale : packoffset(c0.y);
    row_major float4x4 ctime_cb_transform : packoffset(c1);
    float ctime_cb_seed : packoffset(c5);
    float ctime_cb_effect_phase : packoffset(c5.y);
    float ctime_cb_to_base_resolution_multiplier : packoffset(c5.z);
    float ctime_cb_has_mask : packoffset(c5.w);
    float ctime_cb_has_background : packoffset(c6);
    float ctime_cb_is_div_card : packoffset(c6.y);
    float ctime_cb_line_height : packoffset(c6.z);
    float4 ctime_cb_aspect_ratio : packoffset(c7);
    float4 ctime_cb_tex_scale : packoffset(c8);
    float ctime_cb_muddle_frequency : packoffset(c9);
    float4 ctime_cb_muddle_intensity : packoffset(c10);
    float4 ctime_cb_tex_clamp : packoffset(c11);
    float4 ctime_cb_effect_params : packoffset(c12);
    float ctime_cb_shader_type : packoffset(c13);
    float ctime_cb_layers_count : packoffset(c13.y);
    float4 ctime_cb_item_size : packoffset(c14);
    float4 ctime_cb_flash_glow_color : packoffset(c15);
    float4 ctime_cb_hellscape_params : packoffset(c16);
    int ctime_cb_mask_width : packoffset(c17);
    int ctime_cb_mask_height : packoffset(c17.y);
    int ctime_cb_displacement : packoffset(c17.z);
    int ctime_cb_x_displacement : packoffset(c17.w);
    int ctime_cb_y_displacement : packoffset(c18);
    uint ctime_cb_outline : packoffset(c18.y);
    float ctime_cb_outline_max : packoffset(c18.z);
    float ctime_cb_outline_min : packoffset(c18.w);
    float4 ctime_cb_outline_colour : packoffset(c19);
    uint ctime_cb_glow : packoffset(c20);
    float4 ctime_cb_glow_info : packoffset(c21);
    float4 ctime_cb_glow_colour : packoffset(c22);
    float4 ctime_cb_layer_0_speed : packoffset(c23);
    float4 ctime_cb_layer_1_speed : packoffset(c24);
    float4 ctime_cb_layer_2_speed : packoffset(c25);
    float4 ctime_cb_layer_3_speed : packoffset(c26);
    float4 ctime_cb_tex_offset : packoffset(c27);
    uint ctime_cb_poisoned : packoffset(c28);
};

[[vk::binding(12, 0)]] SamplerState SamplerLinearWrapOffsetNoBias : register(s12, space0);
[[vk::binding(0, 5)]] Texture2D<float4> tex : register(t0, space5);
[[vk::binding(1, 5)]] Texture2D<float4> mask_tex : register(t1, space5);

static float4 gl_FragCoord;
static float2 in_var_TEXCOORD0;
static float4 out_var_SV_TARGET;

struct SPIRV_Cross_Input
{
    float2 in_var_TEXCOORD0 : TEXCOORD0;
    float4 gl_FragCoord : SV_Position;
};

struct SPIRV_Cross_Output
{
    float4 out_var_SV_TARGET : SV_Target0;
};

void frag_main()
{
    float4 _43 = tex.Sample(SamplerLinearWrapOffsetNoBias, in_var_TEXCOORD0);
    float _66 = _43.w;
    out_var_SV_TARGET = ApplyUIProcessing(float4(((mask_tex.Sample(SamplerLinearWrapOffsetNoBias, float2((gl_FragCoord.x - float(ctime_cb_x_displacement)) / float(ctime_cb_mask_width), (gl_FragCoord.y - float(ctime_cb_y_displacement)) / float(ctime_cb_mask_height))) * _66) + _43).xyz * ctime_cb_effect_phase, _66).xyz, _66);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    gl_FragCoord = stage_input.gl_FragCoord;
    gl_FragCoord.w = 1.0 / gl_FragCoord.w;
    in_var_TEXCOORD0 = stage_input.in_var_TEXCOORD0;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.out_var_SV_TARGET = out_var_SV_TARGET;
    return stage_output;
}
